site_name: RoyalBunny
site_url: https://regivsbannia.github.io/cite-cn/
site_description: A project description
site_author: RoyalBunny

# 使用Material for MkDocs主题
theme:
  name: material
  logo: images/logo.png  # 自定义徽标路径
  favicon: images/favicon.ico  # 自定义图标路径
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal      
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs # 顶部导航
    - toc.follow # 右侧目录


# 导航栏配置
nav:
  - "主页": index.md
  - "天体物理学笔记":
      - "beacon": beacon.md
  - "研究项目":
      - "测试图片": test_photo\test_photo.md
  - "占星学Astrology": 
      - "test": astrology/test_astrology.md
  - "Minecraft":
      - "BDS": bds\bds.md
  - "客制化":
      - "navi": navi.md
  - "备忘录":
      - "学习": beiwanglu/test_beiwanglu.md
  - "English": https://yy-li.com  # 添加一个外部链接
  - "Contact Me/联系我": https://yy-li.com/connect/

# 额外的配置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/regivsbannia
    - icon: fontawesome/brands/twitter
      link: https://twitter.com

# 插件配置
plugins:
  - search

# Markdown扩展
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js